### PR TITLE
Homework 7

### PR DESCRIPTION
**Pull request by Tailor-AI**
Implemented 2 different logger (File and Console) and added to RecipeApp homework. 

Not sure how to catch all unhandled exceptions but searched and found info about unhandled exception event which I subscribe to before start of RecipeApp form.

### CODE REVIEW

**Comment by Tailor-AI** [comment]
I noticed that I have a catch (Exception ex) if writing to file fails. Will this become infinite loop when it then tries to write that unhandled exception to file again? Perhaps I should change this to only output text message.

**Review by Almantask — CHANGES_REQUESTED** [review]
Please retarget the PR to lesson 4 so that you don't include my own code.

**Comment by Tailor-AI** [comment]
Ok. I changed the base to lesson 4 if this is correct?

**Comment by Almantask** [comment]
> Ok. I changed the base to lesson 4 if this is correct?

Yup, that is correct.

**Review by Almantask — APPROVED** [review]
Yup, looks good

**Pull request closed without merging**
